### ISSUE TITLE
Issue: gdm-authd failed: Authentication failure: could not get user info: user email is required, but was not provided

### ISSUE THREAD

**Issue by token47** [ubuntu/authd#476] opened 2024-08-20 15:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

After (presumably correct) configuration on client and server (entra id) sides, when loggin in, I get the error:

```
2024-08-16T15:11:09.660073+00:00 authd-dt-test gdm-session-worker[2369]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T15:11:09.683967+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
```

### Where does the issue happens

- [X] I can reproduce the issue in the graphical display manager
- [X] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

1. Follow the wiki steps to configure server side (entra id domain with a test user). I tried to not skip any step, including the permissions and allow public client flows.
2. Configure a client, also following the wiki steps. It's a VM with 24.04. More details later.
3. Try to login, get the QR code, go to MS website, authenticate using the user create above
4. Get the login approved, QR code disappears and login continues
5. Get the error described initially.

### Environment
* broker version: 0.1 (10)
* authd version: authd 0.3.1~ppa4
* gnome shell version: 46.3.1-1ubuntu1~24.04.1
* Distribution: Ubuntu
* Distribution version: 24.04

### Log files

```raw
2024-08-16T14:59:54.864777+00:00 authd-dt-test systemd[1]: Starting authd.service - Authd daemon service...
2024-08-16T14:59:54.905875+00:00 authd-dt-test systemd[1]: Started authd.service - Authd daemon service.
2024-08-16T15:00:00.242302+00:00 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
2024-08-16T15:00:52.222540+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:00:52.252239+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:03:16.341153+00:00 authd-dt-test gdm-session-worker[2086]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T15:03:16.363130+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:03:16.368002+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:03:35.023445+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:03:35.028608+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:04:32.395990+00:00 authd-dt-test gdm-session-worker[2135]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T15:04:32.413841+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:04:32.422323+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:07:10.969402+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:07:10.975227+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:07:42.499987+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:07:42.509979+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:08:55.237506+00:00 authd-dt-test gdm-session-worker[2332]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T15:08:55.256992+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:08:55.263335+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:09:37.102007+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:09:37.109275+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:11:09.660073+00:00 authd-dt-test gdm-session-worker[2369]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T15:11:09.683967+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:11:09.691558+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:14:12.133833+00:00 authd-dt-test gdm-authd]: accountsservice: ActUserManager: user (null) has no username (uid: -1)
2024-08-16T15:14:12.139750+00:00 authd-dt-test gnome-shell[1043]: Starting authd protocol
2024-08-16T15:16:54.065083+00:00 authd-dt-test gdm-session-worker[2418]: module returned error: gdm-authd failed: Authentication failure: could not get user info: could not fetch user info: user email is required, but was not provided
2024-08-16T23:07:16.367209+00:00 authd-dt-test snapd[656]: storehelpers.go:923: cannot refresh: snap has no updates available: "authd-msentraid", "core24", "snapd"
```

#### Authd entries:

Nothing that draws attention.

```raw
-- Boot 3a0c8b8709d04cf2ad2ce67a3669684b --
Aug 20 12:35:24 authd-dt-test systemd[1]: Starting authd.service - Authd daemon service...
Aug 20 12:35:24 authd-dt-test systemd[1]: Started authd.service - Authd daemon service.
```

####  MS Entra ID broker entries:

```raw
Aug 16 14:12:14 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 14:12:16 authd-dt-test authd-msentraid.authd-msentraid[890]: time=2024-08-16T14:12:16.588Z level=ERROR msg="could not create broker with provided issuer and client ID: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=utf-8\": invalid character '<' looking for beginning of value"
Aug 16 14:12:16 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 14:12:16 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:16 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Consumed 1.294s CPU time.
Aug 16 14:12:16 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 1.
Aug 16 14:12:16 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 14:12:17 authd-dt-test authd-msentraid.authd-msentraid[1071]: time=2024-08-16T14:12:17.194Z level=ERROR msg="could not create broker with provided issuer and client ID: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=utf-8\": invalid character '<' looking for beginning of value"
Aug 16 14:12:17 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 14:12:17 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:17 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 2.
Aug 16 14:12:17 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 14:12:17 authd-dt-test authd-msentraid.authd-msentraid[1111]: time=2024-08-16T14:12:17.863Z level=ERROR msg="could not create broker with provided issuer and client ID: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=utf-8\": invalid character '<' looking for beginning of value"
Aug 16 14:12:17 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 14:12:17 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:18 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 3.
Aug 16 14:12:18 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 14:12:19 authd-dt-test authd-msentraid.authd-msentraid[1175]: time=2024-08-16T14:12:19.289Z level=ERROR msg="could not create broker with provided issuer and client ID: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=utf-8\": invalid character '<' looking for beginning of value"
Aug 16 14:12:19 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 14:12:19 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:19 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 4.
Aug 16 14:12:19 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 14:12:20 authd-dt-test authd-msentraid.authd-msentraid[1429]: time=2024-08-16T14:12:20.619Z level=ERROR msg="could not create broker with provided issuer and client ID: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=utf-8\": invalid character '<' looking for beginning of value"
Aug 16 14:12:20 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 14:12:20 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:20 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Scheduled restart job, restart counter is at 5.
Aug 16 14:12:20 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Start request repeated too quickly.
Aug 16 14:12:20 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Failed with result 'exit-code'.
Aug 16 14:12:20 authd-dt-test systemd[1]: Failed to start snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 16 15:00:00 authd-dt-test systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 20 12:31:55 authd-dt-test systemd[1]: Stopping snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid...
Aug 20 12:31:55 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Deactivated successfully.
Aug 20 12:31:55 authd-dt-test systemd[1]: Stopped snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msentraid.authd-msentraid.
Aug 20 12:31:55 authd-dt-test systemd[1]: snap.authd-msentraid.authd-msentraid.service: Consumed 7.489s CPU time, 7.5M memory peak, 0B memory swap peak.
```

####  Broker configuration:

```raw
ubuntu@authd-dt-test:~$ cat /var/snap/authd-msentraid/current/broker.conf
[oidc]
issuer = https://login.microsoftonline.com/aefc71c0-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0
client_id = e60f0186-xxxx-xxxx-xxxx-xxxxxxxxxxxx

[users]
# The directory where the home directory will be created for new users.
# Existing users will keep their current directory.
# The user home directory will be created in the format of {home_base_dir}/{username}
home_base_dir = /home

# The username suffixes that are allowed to login via ssh without existing previously in the system.
# The suffixes must be separated by commas.
# ssh_allowed_suffixes = @example.com,@anotherexample.com
```

####  Broker authd configuration:

```raw
ubuntu@authd-dt-test:~$ cat /etc/authd/brokers.d/msentraid.conf
# This section is used by authd to identify and communicate with the broker.
# It should not be edited.
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID
```

### Relevant information

What I'm doing is:

![image](https://github.com/user-attachments/assets/aabe8490-7bb7-4150-9912-f6a3384091eb)

![image](https://github.com/user-attachments/assets/83bcbb6c-6d06-4632-8106-f4a41bd0dab8)

![image](https://github.com/user-attachments/assets/b0193b61-ccbe-40ac-bf2b-f1d06e6a98d4)

Then I get the devicelogin screen:

![image](https://github.com/user-attachments/assets/49896fe5-42e9-4bbd-a577-890d1391614f)

Then I go to MS website and authenticate:

![image](https://github.com/user-attachments/assets/3387a283-991a-4f41-a301-b572f50f8d7c)

I chose the account that is created in the Azure ID portal:

![image](https://github.com/user-attachments/assets/56db6b84-c4fd-487a-a4ed-340da3015f81)

I confirm that I'm logging into a device with that account:

![image](https://github.com/user-attachments/assets/0e3ed28b-ae7b-41dc-a3ee-1777fabcccb7)

At this moment, the Ubuntu side authmatically closes that Device Login screen and returns to the prompt:

![image](https://github.com/user-attachments/assets/f054e1f4-7500-40b0-b1d0-a42c17f5458e)

And I see the error in the log saying that the login failed.

Console -- Short username:
![image](https://github.com/user-attachments/assets/bd5b30f4-f393-478d-b14f-6487cdffac72)
Console -- Long username:
![image](https://github.com/user-attachments/assets/08ea746e-83fe-4d58-bc86-7c57b3b3eca8)

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by adombeck** [comment] 2024-08-21 08:32
Thank you for the detailed report!

> broker version: 0.1 (10)

This looks like you're using the stable channel of the authd-msentraid snap. Please try the edge channel as described [here](https://github.com/ubuntu/authd/wiki/06--Troubleshooting#switch-the-snap-to-the-edge-channel) and try again. Please attach the logs again if the issue still occurs.

**Comment by token47** [comment] 2024-08-21 15:17
Woot! It worked with the --edge release. I got past that point without errors and it prompted for a local password, after created it logged me in.

Now I hit another issue, if I logout and re-login, the local password works but I get a black screen and it does not get me to the gnome desktop. I'll attach some logs next.

**Comment by jibel** [comment] 2024-08-21 15:23
Thanks for confirming that upgrading fixes your issues. FYI, we will do a release to the stable channel before EOW. 

I'm closing this issue, can you file a separate one for the logout/login, provide the logs and detailed steps to reproduce it?

Thank you for your help improving our product.

**Closed by jibel** 2024-08-21 15:23 UTC
Labels: bug, broker

**Comment by token47** [comment] 2024-08-21 15:25
Sure! Thanks.
