### ISSUE TITLE
Issue: QR code does not render in MacOS Terminal (Sonoma 14.6.1)

### ISSUE THREAD

**Issue by bill-taut** [ubuntu/authd#500] opened 2024-08-27 23:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

The QR code displays as a series of ### numbers (not the QR code).

Text encoding in setting is set to Unicode (UTF-8)

### Steps to reproduce

1. Open up a Terminal session on MacOS (I'm using Sonoma 14.6.1)
2. ssh firstname.last@mydomian.com@ubuntubox
3. Choose 2
4. QR code is NOT displayed

#### authd version
```
authd   0.3.3
```

#### authd-msentraid broker version
```
name:      authd-msentraid
summary:   MSEntra ID broker for authd
publisher: Canonical**
store-url: https://snapcraft.io/authd-msentraid
license:   GPL-3.0
description: |
  This is the MS Entra ID broker snap for authd  to provide MS Entra ID OIDC
  based authentication on Ubuntu with authd.
services:
  authd-msentraid: simple, enabled, active
snap-id:      my-id
tracking:     0.x/stable
refresh-date: today at 15:19 PDT
channels:
  0.x/stable:    0.1 2024-08-23 (33) 17MB -
  0.x/candidate: ^                        
  0.x/beta:      ^                        
  0.x/edge:      0.1 2024-08-27 (36) 17MB -
installed:       0.1            (33) 17MB -
```

#### gnome-shell version
```
gnome-shell:
  Installed: 46.0-0ubuntu6~24.04.3
  Candidate: 46.3.1-1ubuntu1~24.04.1
  Version table:
     46.3.1-1ubuntu1~24.04.1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd/ubuntu noble/main amd64 Packages
     46.0-0ubuntu6~24.04.4 500 (phased 20%)
        500 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
 *** 46.0-0ubuntu6~24.04.3 500
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
        100 /var/lib/dpkg/status
     46.0-0ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

#### Distribution
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```

#### Logs
```
[713647.800021] anemone systemd[1]: Starting authd.service - Authd daemon service...
[713647.814043] anemone authd[164643]: WARNING Broker configuration directory "/etc/authd/brokers.d/" does not exist, only local br>
[713647.853370] anemone systemd[1]: Started authd.service - Authd daemon service.
[713647.854038] anemone authd[164643]: 2024/08/27 15:18:31 WARN rpc error: code = NotFound desc =
[713668.856658] anemone authd[164643]: 2024/08/27 15:18:52 WARN rpc error: code = NotFound desc =
[713704.029898] anemone authd[164643]: 2024/08/27 15:19:27 WARN rpc error: code = NotFound desc =
[713704.046980] anemone authd[164643]: 2024/08/27 15:19:27 WARN rpc error: code = NotFound desc =
[713705.594244] anemone systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[713705.744839] anemone authd[164643]: 2024/08/27 15:19:29 WARN rpc error: code = NotFound desc =
[713728.449657] anemone authd[164643]: 2024/08/27 15:19:51 WARN rpc error: code = NotFound desc =
[713728.463977] anemone authd[164643]: 2024/08/27 15:19:51 WARN rpc error: code = NotFound desc =
[713734.797433] anemone authd[164643]: 2024/08/27 15:19:58 WARN rpc error: code = NotFound desc =
[713734.802962] anemone authd[164643]: 2024/08/27 15:19:58 WARN rpc error: code = NotFound desc =
[714371.703173] anemone authd[164643]: 2024/08/27 15:30:35 WARN rpc error: code = NotFound desc =
[714820.273453] anemone authd[164643]: 2024/08/27 15:38:03 WARN rpc error: code = NotFound desc =
[714830.677306] anemone authd[164643]: 2024/08/27 15:38:14 WARN rpc error: code = NotFound desc =
[714830.685172] anemone systemd[1]: Stopping authd.service - Authd daemon service...
[714830.686976] anemone systemd[1]: authd.service: Deactivated successfully.
[714830.687108] anemone systemd[1]: Stopped authd.service - Authd daemon service.
[714830.703573] anemone systemd[1]: Starting authd.service - Authd daemon service...
[714830.759058] anemone systemd[1]: Started authd.service - Authd daemon service.
[714830.765258] anemone authd[165832]: 2024/08/27 15:38:14 WARN rpc error: code = NotFound desc =
[714839.904086] anemone authd[165832]: 2024/08/27 15:38:23 WARN rpc error: code = NotFound desc =
[714839.997129] anemone systemd[1]: Stopping snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msen>
[714840.000487] anemone systemd[1]: snap.authd-msentraid.authd-msentraid.service: Deactivated successfully.
[714840.000852] anemone systemd[1]: Stopped snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[714840.034407] anemone systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[714840.076780] anemone authd[165832]: 2024/08/27 15:38:23 WARN rpc error: code = NotFound desc =
[715025.614122] anemone authd[165832]: 2024/08/27 15:41:29 WARN rpc error: code = NotFound desc =
[715087.938469] anemone authd[165832]: 2024/08/27 15:42:31 WARN rpc error: code = NotFound desc =
[715094.041146] anemone authd[165832]: 2024/08/27 15:42:37 WARN rpc error: code = NotFound desc =
[715094.104798] anemone authd[165832]: 2024/08/27 15:42:37 WARN rpc error: code = NotFound desc =
[715125.155428] anemone authd[165832]: 2024/08/27 15:43:08 WARN rpc error: code = NotFound desc =
[715160.969357] anemone authd[165832]: 2024/08/27 15:43:44 WARN rpc error: code = NotFound desc =
[715164.673477] anemone authd[165832]: 2024/08/27 15:43:48 WARN rpc error: code = NotFound desc =
[715164.745954] anemone systemd[1]: Stopping snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msen>
[715164.749765] anemone systemd[1]: snap.authd-msentraid.authd-msentraid.service: Deactivated successfully.
[715164.750308] anemone systemd[1]: Stopped snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[715164.787677] anemone systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[715164.828672] anemone authd[165832]: 2024/08/27 15:43:48 WARN rpc error: code = NotFound desc =
[715202.724588] anemone authd[165832]: 2024/08/27 15:44:26 WARN rpc error: code = NotFound desc =
[715242.767461] anemone authd[165832]: 2024/08/27 15:45:06 WARN rpc error: code = NotFound desc =
[715252.530130] anemone authd[165832]: 2024/08/27 15:45:16 WARN rpc error: code = NotFound desc =
[715302.530779] anemone authd[165832]: 2024/08/27 15:46:06 WARN rpc error: code = NotFound desc =
[715317.536226] anemone authd[165832]: 2024/08/27 15:46:21 WARN rpc error: code = NotFound desc =
[715322.531828] anemone authd[165832]: 2024/08/27 15:46:26 WARN rpc error: code = NotFound desc =
[715390.734517] anemone authd[165832]: 2024/08/27 15:47:34 WARN rpc error: code = NotFound desc =
[715400.240881] anemone authd[165832]: 2024/08/27 15:47:43 WARN rpc error: code = NotFound desc =
[715403.247643] anemone authd[165832]: 2024/08/27 15:47:46 WARN rpc error: code = NotFound desc =
[715403.256230] anemone authd[165832]: 2024/08/27 15:47:46 WARN rpc error: code = NotFound desc =
[715444.322105] anemone authd[165832]: 2024/08/27 15:48:27 WARN rpc error: code = NotFound desc =
[715450.204697] anemone authd[165832]: 2024/08/27 15:48:33 WARN rpc error: code = NotFound desc =
[715457.459967] anemone authd[165832]: 2024/08/27 15:48:40 WARN rpc error: code = NotFound desc =
[715457.531200] anemone systemd[1]: Stopping snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msen>
[715457.534299] anemone systemd[1]: snap.authd-msentraid.authd-msentraid.service: Deactivated successfully.
[715457.534578] anemone systemd[1]: Stopped snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[715457.579458] anemone systemd[1]: Started snap.authd-msentraid.authd-msentraid.service - Service for snap application authd-msent>
[715457.618441] anemone authd[165832]: 2024/08/27 15:48:41 WARN rpc error: code = NotFound desc =
[715462.031581] anemone authd[165832]: 2024/08/27 15:48:45 WARN rpc error: code = NotFound desc =
[715462.100231] anemone authd[165832]: 2024/08/27 15:48:45 WARN rpc error: code = NotFound desc =
[715477.696911] anemone authd[165832]: 2024/08/27 15:49:01 WARN rpc error: code = NotFound desc =
[715488.795451] anemone authd[165832]: 2024/08/27 15:49:12 WARN rpc error: code = NotFound desc =
[715492.534719] anemone authd[165832]: 2024/08/27 15:49:16 WARN rpc error: code = NotFound desc =
[715570.168801] anemone authd[165832]: 2024/08/27 15:50:33 WARN rpc error: code = NotFound desc =
[715572.535367] anemone authd[165832]: 2024/08/27 15:50:36 WARN rpc error: code = NotFound desc =
[715613.131210] anemone authd[165832]: 2024/08/27 15:51:16 WARN rpc error: code = NotFound desc =
[715616.077298] anemone authd[165832]: 2024/08/27 15:51:19 WARN rpc error: code = NotFound desc =
[715618.563508] anemone authd[165832]: 2024/08/27 15:51:22 WARN rpc error: code = NotFound desc =
[715859.094933] anemone authd[165832]: 2024/08/27 15:55:22 WARN rpc error: code = NotFound desc =
[715861.738080] anemone authd[165832]: 2024/08/27 15:55:25 WARN rpc error: code = NotFound desc =
[715930.236897] anemone authd[165832]: 2024/08/27 15:56:33 WARN rpc error: code = NotFound desc =
[716246.953622] anemone authd[165832]: 2024/08/27 16:01:50 WARN rpc error: code = NotFound desc =
[716276.279206] anemone authd[165832]: 2024/08/27 16:02:19 WARN rpc error: code = NotFound desc =
[716279.431574] anemone authd[165832]: 2024/08/27 16:02:22 WARN rpc error: code = NotFound desc =
[716286.621971] anemone authd[165832]: 2024/08/27 16:02:30 WARN rpc error: code = NotFound desc =
[716289.419677] anemone authd[165832]: 2024/08/27 16:02:32 WARN rpc error: code = NotFound desc =
[716307.912550] anemone authd[165832]: 2024/08/27 16:02:51 WARN rpc error: code = NotFound desc =
[716312.983453] anemone authd[165832]: 2024/08/27 16:02:56 WARN rpc error: code = NotFound desc =
[716315.350194] anemone authd[165832]: 2024/08/27 16:02:58 WARN rpc error: code = NotFound desc =
[716322.546281] anemone authd[165832]: 2024/08/27 16:03:06 WARN rpc error: code = NotFound desc =
[716330.198939] anemone authd[165832]: 2024/08/27 16:03:13 WARN could not get authentication modes: no authentication modes availab>
[716330.262232] anemone authd[165832]: 2024/08/27 16:03:13 WARN rpc error: code = NotFound desc =
[716332.546291] anemone authd[165832]: 2024/08/27 16:03:16 WARN rpc error: code = NotFound desc =
[716345.841025] anemone authd[165832]: 2024/08/27 16:03:29 WARN rpc error: code = NotFound desc =
[716352.301775] anemone authd[165832]: 2024/08/27 16:03:35 WARN could not get authentication modes: no authentication modes availab>
[716352.368864] anemone authd[165832]: 2024/08/27 16:03:35 WARN rpc error: code = NotFound desc =
[716352.546577] anemone authd[165832]: 2024/08/27 16:03:36 WARN rpc error: code = NotFound desc =
[716697.956063] anemone authd[165832]: 2024/08/27 16:09:21 WARN rpc error: code = NotFound desc =
[718378.346927] anemone authd[165832]: 2024/08/27 16:37:21 WARN rpc error: code = NotFound desc =
```

#### /etc/authd/brokers.d/msentraid.conf
```
# This section is used by authd to identify and communicate with the broker.
# It should not be edited.
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID
```

#### authd-msentraid configuration
```
[oidc]
issuer = https://login.microsoftonline.com/<UUID redacted>/v2.0
client_id = <UUID redacted>

[users]
# The directory where the home directory will be created for new users.
# Existing users will keep their current directory.
# The user home directory will be created in the format of {home_base_dir}/{username}
home_base_dir = /home

# The username suffixes that are allowed to login via ssh without existing previously in the system.
# The suffixes must be separated by commas.
ssh_allowed_suffixes = @mydomain.com
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment] 2024-09-06 15:01
duplicate of #497

**Closed** 2024-09-06 15:09 UTC
Labels: bug, high
